# Generated by Django 4.2.4 on 2023-09-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('total_product', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='media/img_product')),
            ],
        ),
    ]
