# Generated by Django 4.2.4 on 2023-09-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
